### ISSUE TITLE
Look at break out of sections

### ISSUE THREAD

**Issue by e-lo** [e-lo/travel-modeling-as-science#1]
@billyc will look at the breakout of various sections in the proposal.

**Comment by billyc** [comment]
@e-lo this breakout looks fine, but reveals something weird/unanticipated in Dave's original proposal: the new "starting point" section describes a specific proposed model structure, and then later in decision-making there is another "starting point" section which proposes using ActivitySim.

After approving this chapter breakout we'll need to extract the MPO-style model development as an *example project to be incubated*, and not the single end product.  But yeah, we already knew that. =)

**Comment by billyc** [comment]
@e-lo Which is to say, that there should probably be a new section which is "Example incubated project".

**Comment by e-lo** [comment]
+1
