### ISSUE TITLE
Review bylaws and other docs from 2013

### ISSUE THREAD

**Issue by billyc** [e-lo/travel-modeling-as-science#2]

**Comment by billyc** [comment]
@e-lo i've reviewed all the docs in the shared os-planning folder, including the bylaws.  There are lots of margin comments in the bylaws document, most of which are pretty easy to just decide on. We should chat about the following though:

* State of incorporation - Client was going to do research? Should we stick to Delaware or move to California?
* Must each Project Management Committee chairman be a board member? That seems like it could be delegated to a regular member
* We don't need nine board members.

**Comment by e-lo** [comment]
@billyc :  

 - State of incorporation: I suggest we ask a lawyer.  
 - On PMC chairmen be a board member: I agree that this is overkill.  Maybe just "a member in good standing"?
 - Agree on # of board members. Ideally the bylaws would actually be silent on that.

**Comment by billyc** [comment]
all seems good to me. +1

**Comment by e-lo** [comment]
https://github.com/e-lo/travel-modeling-as-science/blob/foundation/A-foundation-structure.md
